import type { Metadata } from "next";
import "./theme-config.css"
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import "@radix-ui/themes/styles.css";
import { Theme, ThemePanel } from "@radix-ui/themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const inter = Inter({
  subsets:['latin'],
  	variable: "--font-inter",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={` ${geistSans.variable} ${geistMono.variable} ${inter.variable} h-full antialiased`}
    >
      <body >
        <Theme accentColor="violet">
          <Navbar />
          <main className="p-5">{children}</main>
          {/* <ThemePanel/> */}
        </Theme>
      </body>
    </html>
  );
}
